### ISSUE TITLE
Idea de Anteproyecto 

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-6-anteproyecto-equipo-daniel#1]
Daniel Velasco López
Edgar Mauricio Sarmiento Ruiz
Sandy Marissa García Santiago

[Anteproyecto .pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-anteproyecto-equipo-daniel/files/9700887/Anteproyecto.pdf)

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 6 
"ANTEPROYECTO"
DEL 20% DE LA ACTIVIDAD, DE ACUERDO A LA RUBRICA OBTUVISTE EL 18.56%

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 6
"ANTEPROYECTO"
DEL 20% DE LA ACTIVIDAD, DE ACUERDO A LA RUBRICA OBTUVISTE EL 18.96%

**Comment by josealfredo79** [comment]
Mejoras del proyecto
Estadisticas no le sirivirian mucho....
Se debe utilizar smartcontracts

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
